// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/backup": {
    params: {};
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/collections/:handle" | "/products/:handle" | "/backup" | "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/collections.$handle.jsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/products.$handle.jsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/" | "/backup";
  };
  "routes/_index.backup.jsx": {
    id: "routes/_index.backup";
    page: "/backup";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/Users/andrealmeida/Desktop/gueth-ecommerce/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json" | "/";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx": {
    id: "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/collections.$handle": typeof import("./app/routes/collections.$handle.jsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/_index.backup": typeof import("./app/routes/_index.backup.jsx");
  "/Users/andrealmeida/Desktop/gueth-ecommerce/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout": unknown;
  "vite/virtual-routes/routes/graphiql": unknown;
  "vite/virtual-routes/routes/subrequest-profiler": unknown;
  "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json": unknown;
  "vite/virtual-routes/routes/index": unknown;
};